# Generated by Django 2.1.2 on 2018-11-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='study',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subtheme',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created_by',
        ),
    ]
