# Generated by Django 2.1.2 on 2018-11-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20181122_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.Theme'),
        ),
    ]
