# Generated by Django 2.1.2 on 2019-03-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190304_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='publish',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Private', max_length=7, verbose_name='Publish'),
        ),
    ]
