# Generated by Django 2.1.2 on 2018-11-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20181122_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='resource',
        ),
        migrations.AddField(
            model_name='study',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.Resource'),
        ),
    ]
