# Generated by Django 2.1.2 on 2019-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_study_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
