# Generated by Django 2.1.2 on 2018-12-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20181122_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='sub_category',
            field=models.ManyToManyField(to='study.SubCategory'),
        ),
        migrations.AlterField(
            model_name='study',
            name='sub_theme',
            field=models.ManyToManyField(to='study.SubTheme'),
        ),
    ]
