# Generated by Django 2.1.2 on 2019-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20181220_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='quality',
            field=models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Medium', 'Medium')], default='Low', max_length=6, verbose_name='Quality'),
        ),
    ]
