# Generated by Django 2.1.2 on 2019-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_study_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='summary',
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Study Summary'),
        ),
    ]
