# Generated by Django 2.1.2 on 2019-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20190406_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='author',
            field=models.CharField(max_length=555, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='study',
            name='link',
            field=models.CharField(max_length=555, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=555, verbose_name='Title'),
        ),
    ]
